// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMexq0ZPzU3MGoh72UfU0QOwVDkVCxv_0',
    appId: '1:543778084106:android:6a6c7b2a2d11d7535816f3',
    messagingSenderId: '543778084106',
    projectId: 'notes-pandupanda-project',
    storageBucket: 'notes-pandupanda-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvBodCE9vzMPBW2msMqQWyD7pmU61LxHo',
    appId: '1:543778084106:ios:8cc5c2db0a693b935816f3',
    messagingSenderId: '543778084106',
    projectId: 'notes-pandupanda-project',
    storageBucket: 'notes-pandupanda-project.appspot.com',
    iosClientId: '543778084106-olhh64m9i9udcc28b86jiv4t1lif83gp.apps.googleusercontent.com',
    iosBundleId: 'com.pandupanda.notes',
  );
}
